"use client";

import React from 'react';
import { 
  ScrollText, 
  Lock, 
  FileText, 
  ShieldAlert, 
  Gavel, 
  Scale, 
  AlertTriangle,
  Mail,

} from 'lucide-react';
import HomeLayout from '@/components/layout/homelayout';


const TermsHeader = () => (
  <section className="pt-32 pb-16 px-4 md:px-8 w-full text-center relative overflow-hidden bg-[#F2F2F7]">
    {/* Background Glow */}
    <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[800px] h-[600px] bg-orange-200/40 rounded-full blur-[120px] pointer-events-none"></div>
    
    <div className="relative z-10 max-w-4xl mx-auto">
      <div className="inline-flex items-center gap-2 bg-white/80 backdrop-blur-sm border border-orange-100 rounded-full px-5 py-2 mb-8 shadow-sm">
        <ScrollText size={16} className="text-orange-600" />
        <span className="text-xs font-bold text-orange-700 uppercase tracking-wide">Legal Agreement</span>
      </div>
      
      <h1 className="text-4xl md:text-6xl font-bold text-[#1C1C1E] tracking-tight mb-6">
        Terms and Conditions
      </h1>
      <p className="text-xl text-[#8E8E93] max-w-2xl mx-auto">
        Please read these terms carefully before using our platform.
      </p>
      <p className="text-sm font-medium text-orange-600 mt-4">Last Updated: january 01, 2026</p>
    </div>
  </section>
);

const TermsBody = () => {
  const sections = [
    {
      id: "acceptance",
      title: "1. Acceptance of Terms",
      icon: ScrollText,
      content: (
        <>
          <p className="mb-4">
            By accessing, registering for, or using the services provided by <strong>Logicore Inc.</strong> (&quot;Logicore&quot;, &quot;we&quot;, &quot;us&quot;, or &quot;our&quot;) via the website <strong>Logicor Inc</strong> (the &quot;Site&quot;) and its related applications and services (collectively, the &quot;Service&quot;), you (&quot;User&quot;, &quot;Subscriber&quot;, or &quot;you&quot;) agree to be bound by these Terms and Conditions (&quot;Terms&quot;).
          </p>
          <p className="mb-4 font-semibold text-[#1C1C1E]">
            IF YOU DO NOT AGREE TO THESE TERMS, DO NOT USE THE SERVICE.
          </p>
          <p>
            We reserve the right to modify these Terms at any time. Your continued use of the Service constitutes acceptance of such modifications.
          </p>
        </>
      )
    },
    {
      id: "ai-disclaimer",
      title: "2. AI & Legal Advice Disclaimer",
      icon: AlertTriangle,
      content: (
        <>
          <div className="bg-amber-50 border-l-4 border-amber-500 p-6 rounded-r-xl mb-6 text-amber-900 text-sm leading-relaxed">
            <strong>CRITICAL NOTICE:</strong> Nexion-ERP is a technology provider, not a law firm. The Service does not constitute legal advice.
          </div>
          <p className="mb-4">
            <strong>2.1 Not Legal Advice:</strong> The Service, including its Artificial Intelligence (&quot;AI&quot;) features (e.g., Risk Analysis, Context-Aware Drafting, Judge Analytics, Predictive Insights), provides information and tools for assistance purposes only. The output generated by the Service (&quot;Output&quot;) does <strong>not</strong> constitute legal advice, legal opinion, or a recommendation on any specific legal matter.
          </p>
          <p className="mb-4">
            <strong>2.2 Professional Responsibility:</strong> You acknowledge that you are a qualified legal professional or are using the Service under the supervision of one. You retain full and sole responsibility for:
          </p>
          <ul className="list-disc pl-6 mb-4 space-y-2 text-[#48484A]">
            <li>Verifying the accuracy, completeness, and currency of any Output generated by the AI.</li>
            <li>Applying your independent professional judgment to any Output.</li>
            <li>Ensuring that any documents drafted or reviewed using the Service comply with applicable laws, court rules, and professional standards.</li>
          </ul>
          <p>
            <strong>2.3 AI Limitations:</strong> You acknowledge that AI models may produce &quot;hallucinations&quot; (factually incorrect or non-existent case law/statutes). Nexion-ERP explicitly disclaims liability for errors, omissions, or inaccuracies in AI-generated content.
          </p>
        </>
      )
    },
    {
      id: "account",
      title: "3. Account Registration & Security",
      icon: Lock,
      content: (
        <>
          <p className="mb-4">
            <strong>3.1 Eligibility:</strong> You must be at least 18 years of age to use the Service. By creating an account, you warrant that you are a licensed attorney or an authorized employee of a legal entity.
          </p>
          <p className="mb-4">
            <strong>3.2 Credentials:</strong> You are responsible for maintaining the confidentiality of your login credentials. You are fully responsible for all activities that occur under your account. Nexion-ERP is not liable for any loss or damage arising from your failure to protect your account.
          </p>
          <p>
            <strong>3.3 Data Accuracy:</strong> You agree to provide accurate, current, and complete information during the registration process and to update such information to keep it accurate, current, and complete.
          </p>
        </>
      )
    },
    {
      id: "usage",
      title: "4. Acceptable Use Policy",
      icon: FileText,
      content: (
        <>
          <p className="mb-4">You agree NOT to use the Service to:</p>
          <ul className="list-disc pl-6 mb-4 space-y-2 text-[#48484A]">
            <li>Violate any applicable local, state, national, or international law or regulation.</li>
            <li>Infringe the rights of any third party, including intellectual property, privacy, or publicity rights.</li>
            <li>Upload, transmit, or store any content that is unlawful, harmful, threatening, abusive, harassment, tortious, defamatory, or otherwise objectionable.</li>
            <li>Reverse engineer, decompile, disassemble, or attempt to derive the source code of the Service.</li>
            <li>Use the Service to build a competitive product or service.</li>
          </ul>
        </>
      )
    },
    {
      id: "liability",
      title: "5. Limitation of Liability",
      icon: ShieldAlert,
      content: (
        <>
          <div className="bg-red-50 border border-red-100 p-6 rounded-2xl mb-6">
            <p className="text-sm text-red-800 font-bold uppercase mb-2">Read Carefully</p>
            <p className="text-sm text-red-900 leading-relaxed">
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL Nexion-ERP INC., ITS AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE FOR ANY INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES, INCLUDING WITHOUT LIMITATION DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA, OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR RELATING TO THE USE OF, OR INABILITY TO USE, THE SERVICE.
            </p>
          </div>
          <p className="mb-4">
            <strong>5.1 Monetary Cap:</strong> Under no circumstances will Nexion-ERP&apos;s total liability to you for all claims arising out of or relating to these terms or your use of the service exceed the greater of: (a) the amount you have paid to Nexion-ERP for use of the service in the twelve (12) months prior to the act that gave rise to the liability, or (b) ₹10,000 INR.
          </p>
          <p>
            <strong>5.2 Basis of the Bargain:</strong> You acknowledge that Nexion-ERP has set its prices and entered into these Terms in reliance upon the limitations of liability and the disclaimers of warranties and damages set forth herein, and that the same form an essential basis of the bargain between the partie.
          </p>
        </>
      )
    },
    {
      id: "indemnification",
      title: "6. Indemnification",
      icon: Gavel,
      content: (
        <>
          <p>
            You agree to defend, indemnify and hold harmless Nexion-ERP and its licensee and licensors, and their employees, contractors, agents, officers and directors, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney&apos;s fees), resulting from or arising out of:
          </p>
          <ul className="list-disc pl-6 mt-4 space-y-2 text-[#48484A]">
            <li>Your use and access of the Service, by you or any person using your account and password;</li>
            <li>A breach of these Terms;</li>
            <li>Any claim that your use of the Service (including AI outputs used in your practice) caused damage to a third party (including your clients).</li>
          </ul>
        </>
      )
    },
    {
      id: "payment",
      title: "7. Fees and Payment",
      icon: Scale, 
      content: (
        <>
          <p className="mb-4">
            <strong>7.1 Subscription:</strong> Use of the Service is subject to the subscription fees set forth on our Pricing page. Fees are billed in advance on a monthly or yearly basis and are non-refundable.
          </p>
          <p className="mb-4">
            <strong>7.2 Taxes:</strong> You are responsible for all applicable taxes, levies, or duties imposed by taxing authorities.
          </p>
          <p>
            <strong>7.3 Rate Changes:</strong> Nexion-ERP reserves the right to modify pricing at any time, provided that we will notify you at least 30 days in advance of any price increase affecting your existing subscription.
          </p>
        </>
      )
    }
  ];

  return (
    <section className="py-12 px-4 md:px-8 bg-white -mt-8 pb-5">
      {/* Changed max-w-7xl mx-auto to w-full to utilize full width as requested */}
      <div className="w-full">
        <div className="space-y-8">
          {sections.map((section) => (
            <div 
              key={section.id} 
              id={section.id} 
              className="bg-white rounded-[32px] p-8 md:p-12 border border-[#E5E5EA] shadow-sm hover:shadow-md transition-shadow duration-300"
            >
              <div className="flex items-start md:items-center gap-5 mb-8 pb-6 border-b border-[#E5E5EA]">
                <div className="w-14 h-14 bg-orange-50 rounded-2xl flex items-center justify-center text-orange-600 shrink-0">
                  <section.icon size={28} />
                </div>
                <h2 className="text-2xl md:text-3xl font-bold text-[#1C1C1E]">{section.title}</h2>
              </div>
              
              <div className="prose prose-slate max-w-none text-[#48484A] leading-relaxed text-base md:text-lg">
                {section.content}
              </div>
            </div>
          ))}
        </div>

        {/* Contact Block */}
        <div className="mt-5 p-2 bg-[#F2F2F7] rounded-[32px] text-center border border-[#E5E5EA]">
          <div className="inline-flex items-center justify-center w-12 h-12 bg-white rounded-full text-orange-600 mb-4 shadow-sm">
             <Mail size={20} />
          </div>
          <h3 className="text-xl font-bold text-[#1C1C1E] mb-2">Questions regarding these terms?</h3>
          <p className="text-[#8E8E93] mb-6">Please contact our legal department before using the service.</p>
          <a href="mailto:ogdine@cfcsoftware.com" className="inline-flex items-center justify-center px-8 py-3 bg-white text-orange-600 border border-[#E5E5EA] rounded-full font-bold hover:bg-orange-50 transition-colors">
            ogdine@cfcsoftware.com
          </a>
        </div>
      </div>
    </section>
  );
};

export default function TermsAndConditions() {
  return (
    <HomeLayout>
      <div className="bg-[#F9F9F9] min-h-screen font-sans selection:bg-orange-100 selection:text-orange-900">
        <TermsHeader />
        <TermsBody />
      </div>
    </HomeLayout>
  );
}